name: Reusable workflow to make a literate-octo-umbrella release
description: Make a release

on:
  workflow_dispatch:
    inputs:
      git-tag:
        description: Git tag to release
        type: string
        required: true
      python-version:
        type: string
        required: true

jobs:
  make-release:
    uses: suvayu/literate-octo-umbrella/.github/workflows/make-release.yml@master
    with:
      python-version: ${{ inputs.python-version }}
      git-tag: ${{ inputs.git-tag }}
