name: Reusable workflow to make a literate-octo-umbrella release
description: Make a release

on:
  workflow_dispatch:
    inputs:
      git-tag:
        description: Git tag to release
        type: string
        required: true
      python-version:
        type: string
        required: true

jobs:
  make-release:
    runs-on: linux-latest
    steps:
    - name: Make literate-octo-umbrella release
      run: |
        gh workflow run \
          --repo suvayu/literate-octo-umbrella make-release.yml \
          -F git-tag=${{ inputs.git-tag }} \
          -F python-version=${{ inputs.python-version }}
